=== BrainBuzzer/netjson/schema/network-routes.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "type",
    "protocol",
    "version",
    "metric",
    "routes"
  ],
  "properties": {
    "type": {
      "id": "type",
      "type": "string",
      "default": "NetworkRoutes",
      "pattern": "NetworkRoutes"
    },
    "protocol": {
      "id": "protocol",
      "type": "string"
    },
    "version": {
      "id": "version",
      "type": "string"
    },
    "metric": {
      "id": "metric",
      "type": "string"
    },
    "revision": {
      "id": "revision",
      "type": "string"
    },
    "router_id": {
      "id": "router_id",
      "type": "string"
    },
    "topology_id": {
      "id": "topology_id",
      "type": "string"
    },
    "routes": {
      "id": "routes",
      "type": "array",
      "title": "Routes",
      "uniqueItems": true,
      "additionalItems": true,
      "items": {
        "type": "object",
        "title": "Route",
        "additionalProperties": true,
        "required": [
          "destination",
          "next",
          "device",
          "cost"
        ],
        "properties": {
          "destination": {
            "id": "destination",
            "type": "string"
          },
          "next": {
            "id": "next",
            "type": "string"
          },
          "device": {
            "id": "device",
            "type": "string"
          },
          "cost": {
            "id": "cost",
            "type": "float"
          },
          "source": {
            "id": "source",
            "type": "string"
          },
          "cost_txt": {
            "id": "cost_txt",
            "type": "string"
          }
        }
      }
    }
  }
}

=== BrainBuzzer/netjson/examples/network-routes.json
{
    "type": "NetworkRoutes",
    "protocol": "PROTOCOL-NAME",
    "version": "PROTOCOL-VERSION",
    "metric": "PROTOCOL-METRIC",
    "router_id": "ROUTER-ID",
    "routes": [
        {
            "destination": "ID",
            "source": "ID",
            "next" : "ID",
            "device": "DEVICE",
            "cost": 1
        }
    ]
}
